// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkNewJoinCode = `-- name: CheckNewJoinCode :many
SELECT id
FROM rooms
WHERE join_code = $1
`

func (q *Queries) CheckNewJoinCode(ctx context.Context, joinCode string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, checkNewJoinCode, joinCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByUser = `-- name: GetRoomsByUser :many
SELECT id, name, description, join_code, created_at, updated_at
FROM rooms
WHERE owner_id = $1
`

type GetRoomsByUserRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetRoomsByUser(ctx context.Context, ownerID uuid.UUID) ([]GetRoomsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomsByUserRow
	for rows.Next() {
		var i GetRoomsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (owner_id, name, description, join_code)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, join_code, created_at, updated_at
`

type InsertRoomParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
}

type InsertRoomRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (InsertRoomRow, error) {
	row := q.db.QueryRowContext(ctx, insertRoom,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.JoinCode,
	)
	var i InsertRoomRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET 
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE owner_id = $1
    AND join_code = $2
RETURNING id, name, description, join_code, created_at, updated_at
`

type UpdateRoomParams struct {
	OwnerID     uuid.UUID      `json:"owner_id"`
	JoinCode    string         `json:"join_code"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

type UpdateRoomRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (UpdateRoomRow, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.OwnerID,
		arg.JoinCode,
		arg.Name,
		arg.Description,
	)
	var i UpdateRoomRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
