#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

cd "$SCRIPT_DIR"

if [[ "$1" == "start" ]]; then
    bash ./scripts/start.sh
fi

if [[ "$1" == "generate-sqlc" ]]; then
    bash ./scripts/generate-sqlc.sh
fi

if [[ "$1" == "connect-psql" ]]; then
    bash ./scripts/connect-psql.sh
fi

if [[ "$1" == "rebuild" ]]; then
    bash ./scripts/rebuild.sh
fi

if [[ "$1" == "connect-redis" ]]; then
    bash ./scripts/connect-redis.sh
fi
