// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: comprehension_scores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getComprehensionScoresBySession = `-- name: GetComprehensionScoresBySession :many
SELECT id, session_id, user_id, score, created_at
FROM comprehension_scores
WHERE session_id = $1
`

func (q *Queries) GetComprehensionScoresBySession(ctx context.Context, sessionID uuid.UUID) ([]ComprehensionScore, error) {
	rows, err := q.db.QueryContext(ctx, getComprehensionScoresBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComprehensionScore
	for rows.Next() {
		var i ComprehensionScore
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Score,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertComprehensionScore = `-- name: InsertComprehensionScore :one
INSERT INTO comprehension_scores (user_id, session_id, score)
VALUES ($1, $2, $3)
RETURNING id, session_id, user_id, score, created_at
`

type InsertComprehensionScoreParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	Score     int16     `json:"score"`
}

func (q *Queries) InsertComprehensionScore(ctx context.Context, arg InsertComprehensionScoreParams) (ComprehensionScore, error) {
	row := q.db.QueryRowContext(ctx, insertComprehensionScore, arg.UserID, arg.SessionID, arg.Score)
	var i ComprehensionScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}
