// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: middleware_checks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const checkCanDeleteQuestion = `-- name: CheckCanDeleteQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM questions q
    JOIN sessions s
        ON q.session_id = s.id
    WHERE q.id = $1
        AND (
            q.user_id = $2 OR
            s.owner_id = $2
        )
)
`

type CheckCanDeleteQuestionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckCanDeleteQuestion(ctx context.Context, arg CheckCanDeleteQuestionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCanDeleteQuestion, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkCanDeleteQuestionLike = `-- name: CheckCanDeleteQuestionLike :one
SELECT EXISTS (
    SELECT 1
    FROM question_likes
    WHERE user_id = $1
)
`

func (q *Queries) CheckCanDeleteQuestionLike(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCanDeleteQuestionLike, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkOwnsQuestion = `-- name: CheckOwnsQuestion :one
SELECT EXISTS (
    SELECT 1
    FROM questions
    WHERE id = $1
        AND user_id = $2
)
`

type CheckOwnsQuestionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckOwnsQuestion(ctx context.Context, arg CheckOwnsQuestionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkOwnsQuestion, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkQuestionBelongsToSession = `-- name: CheckQuestionBelongsToSession :one
SELECT EXISTS (
    SELECT 1
    FROM questions
    WHERE id = $1
        AND session_id = $2
)
`

type CheckQuestionBelongsToSessionParams struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) CheckQuestionBelongsToSession(ctx context.Context, arg CheckQuestionBelongsToSessionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkQuestionBelongsToSession, arg.ID, arg.SessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkRoomMembershipByRoomId = `-- name: CheckRoomMembershipByRoomId :one
SELECT EXISTS (
    SELECT 1
    FROM rooms r
    LEFT JOIN room_memberships rm
        ON rm.room_id = r.id
        AND rm.user_id = $2
    WHERE r.id = $1
        AND (r.owner_id = $2 OR rm.user_id IS NOT NULL)
)
`

type CheckRoomMembershipByRoomIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckRoomMembershipByRoomId(ctx context.Context, arg CheckRoomMembershipByRoomIdParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkRoomMembershipByRoomId, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkRoomMembershipBySessionId = `-- name: CheckRoomMembershipBySessionId :one
SELECT EXISTS (
    SELECT 1
    FROM rooms r
    LEFT JOIN room_memberships rm
        ON r.id = rm.room_id
        AND rm.user_id = $2
    JOIN sessions s
        ON r.id = s.room_id
    WHERE s.id = $1
        AND (r.owner_id = $2 OR rm.user_id IS NOT NULL)
)
`

type CheckRoomMembershipBySessionIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckRoomMembershipBySessionId(ctx context.Context, arg CheckRoomMembershipBySessionIdParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkRoomMembershipBySessionId, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkRoomOwnershipByRoomId = `-- name: CheckRoomOwnershipByRoomId :one
SELECT EXISTS (
    SELECT 1
    FROM rooms
    WHERE id = $1
        AND owner_id = $2
)
`

type CheckRoomOwnershipByRoomIdParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CheckRoomOwnershipByRoomId(ctx context.Context, arg CheckRoomOwnershipByRoomIdParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkRoomOwnershipByRoomId, arg.ID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkRoomOwnershipBySessionId = `-- name: CheckRoomOwnershipBySessionId :one
SELECT EXISTS (
    SELECT 1
    FROM rooms r
    JOIN sessions s
        ON r.id = s.room_id
    WHERE s.id = $1
        AND r.owner_id = $2
)
`

type CheckRoomOwnershipBySessionIdParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CheckRoomOwnershipBySessionId(ctx context.Context, arg CheckRoomOwnershipBySessionIdParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkRoomOwnershipBySessionId, arg.ID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSessionActive = `-- name: CheckSessionActive :one
SELECT EXISTS (
    SELECT 1
    FROM sessions
    WHERE id = $1
        AND is_active = TRUE
)
`

func (q *Queries) CheckSessionActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSessionActive, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSessionMembership = `-- name: CheckSessionMembership :one
SELECT EXISTS (
SELECT 1
FROM sessions s
WHERE s.id = $1
  AND (
      s.owner_id = $2
      OR EXISTS (
          SELECT 1
          FROM session_memberships sm
          WHERE sm.session_id = s.id
            AND sm.user_id = $2
      )
  )
)
`

type CheckSessionMembershipParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CheckSessionMembership(ctx context.Context, arg CheckSessionMembershipParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSessionMembership, arg.ID, arg.OwnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSessionMembershipOnly = `-- name: CheckSessionMembershipOnly :one
SELECT EXISTS (
    SELECT 1
    FROM sessions s
    LEFT JOIN session_memberships sm
        ON s.id = sm.session_id
        AND sm.user_id = $2
    WHERE s.id = $1
        AND sm.user_id IS NOT NULL
)
`

type CheckSessionMembershipOnlyParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckSessionMembershipOnly(ctx context.Context, arg CheckSessionMembershipOnlyParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSessionMembershipOnly, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
