// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ComprehensionScore struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
	Score     int16     `json:"score"`
	CreatedAt time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	IsRevoked bool      `json:"is_revoked"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Room struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RoomMembership struct {
	UserID   uuid.UUID `json:"user_id"`
	RoomID   uuid.UUID `json:"room_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type Session struct {
	ID        uuid.UUID    `json:"id"`
	RoomID    uuid.UUID    `json:"room_id"`
	OwnerID   uuid.UUID    `json:"owner_id"`
	Name      string       `json:"name"`
	IsActive  bool         `json:"is_active"`
	StartedAt time.Time    `json:"started_at"`
	EndedAt   sql.NullTime `json:"ended_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type SessionMembership struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	JoinedAt  time.Time `json:"joined_at"`
}

type User struct {
	ID              uuid.UUID `json:"id"`
	Email           string    `json:"email"`
	PasswordHash    string    `json:"password_hash"`
	Role            string    `json:"role"`
	Username        string    `json:"username"`
	IsEmailVerified bool      `json:"is_email_verified"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
