// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: question_likes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteQuestionLike = `-- name: DeleteQuestionLike :one
DELETE FROM question_likes ql
USING questions q
WHERE ql.question_id = q.id
    AND ql.user_id = $1
    AND ql.question_id = $2
    AND q.session_id = $3
RETURNING ql.id
`

type DeleteQuestionLikeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
	SessionID  uuid.UUID `json:"session_id"`
}

func (q *Queries) DeleteQuestionLike(ctx context.Context, arg DeleteQuestionLikeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteQuestionLike, arg.UserID, arg.QuestionID, arg.SessionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getQuestionLikesBySession = `-- name: GetQuestionLikesBySession :many
SELECT ql.id, ql.user_id, ql.question_id, ql.created_at
FROM question_likes ql
JOIN questions q
    ON ql.question_id = q.id
    WHERE session_id = $1
`

func (q *Queries) GetQuestionLikesBySession(ctx context.Context, sessionID uuid.UUID) ([]QuestionLike, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionLikesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionLike
	for rows.Next() {
		var i QuestionLike
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuestionLike = `-- name: InsertQuestionLike :one
INSERT INTO question_likes (user_id, question_id)
VALUES (
    $1,
    $2
)
RETURNING id, user_id, question_id, created_at
`

type InsertQuestionLikeParams struct {
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) InsertQuestionLike(ctx context.Context, arg InsertQuestionLikeParams) (QuestionLike, error) {
	row := q.db.QueryRowContext(ctx, insertQuestionLike, arg.UserID, arg.QuestionID)
	var i QuestionLike
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.CreatedAt,
	)
	return i, err
}
