// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (user_id, session_id, text)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, session_id, text, is_answered, answered_at, created_at, updated_at
`

type InsertQuestionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	Text      string    `json:"text"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, insertQuestion, arg.UserID, arg.SessionID, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Text,
		&i.IsAnswered,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
