// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: questions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE user_id = $1
    AND id = $2
    AND session_id = $3
`

type DeleteQuestionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, arg.UserID, arg.ID, arg.SessionID)
	return err
}

const getQuestionsBySession = `-- name: GetQuestionsBySession :many
SELECT id, user_id, session_id, text, is_answered, answered_at, created_at, updated_at
FROM questions
WHERE session_id = $1
`

func (q *Queries) GetQuestionsBySession(ctx context.Context, sessionID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getQuestionsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.Text,
			&i.IsAnswered,
			&i.AnsweredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (user_id, session_id, text)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, user_id, session_id, text, is_answered, answered_at, created_at, updated_at
`

type InsertQuestionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
	Text      string    `json:"text"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, insertQuestion, arg.UserID, arg.SessionID, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Text,
		&i.IsAnswered,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET text = COALESCE($3, text),
    updated_at = NOW()
WHERE user_id = $1
    AND id = $2
RETURNING id, user_id, session_id, text, is_answered, answered_at, created_at, updated_at
`

type UpdateQuestionParams struct {
	UserID uuid.UUID      `json:"user_id"`
	ID     uuid.UUID      `json:"id"`
	Text   sql.NullString `json:"text"`
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion, arg.UserID, arg.ID, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.Text,
		&i.IsAnswered,
		&i.AnsweredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
