// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: replies.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteReply = `-- name: DeleteReply :one
DELETE FROM replies r
USING questions q
WHERE r.question_id = q.id
    AND r.user_id = $1
    AND r.id = $2
    AND q.session_id = $3
RETURNING r.id
`

type DeleteReplyParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) DeleteReply(ctx context.Context, arg DeleteReplyParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteReply, arg.UserID, arg.ID, arg.SessionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getRepliesBySession = `-- name: GetRepliesBySession :many
SELECT r.id, r.user_id, r.question_id, r.parent_id, r.text, r.created_at, r.updated_at
FROM replies r
JOIN questions q
    ON r.question_id = q.id
    WHERE session_id = $1
`

func (q *Queries) GetRepliesBySession(ctx context.Context, sessionID uuid.UUID) ([]Reply, error) {
	rows, err := q.db.QueryContext(ctx, getRepliesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reply
	for rows.Next() {
		var i Reply
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuestionID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReply = `-- name: InsertReply :one
INSERT INTO replies (user_id, question_id, parent_id, text)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, user_id, question_id, parent_id, text, created_at, updated_at
`

type InsertReplyParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	QuestionID uuid.UUID     `json:"question_id"`
	ParentID   uuid.NullUUID `json:"parent_id"`
	Text       string        `json:"text"`
}

func (q *Queries) InsertReply(ctx context.Context, arg InsertReplyParams) (Reply, error) {
	row := q.db.QueryRowContext(ctx, insertReply,
		arg.UserID,
		arg.QuestionID,
		arg.ParentID,
		arg.Text,
	)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReply = `-- name: UpdateReply :one
UPDATE replies
SET text = COALESCE($3, text),
    updated_at = NOW()
WHERE user_id = $1
    AND id = $2
RETURNING id, user_id, question_id, parent_id, text, created_at, updated_at
`

type UpdateReplyParams struct {
	UserID uuid.UUID      `json:"user_id"`
	ID     uuid.UUID      `json:"id"`
	Text   sql.NullString `json:"text"`
}

func (q *Queries) UpdateReply(ctx context.Context, arg UpdateReplyParams) (Reply, error) {
	row := q.db.QueryRowContext(ctx, updateReply, arg.UserID, arg.ID, arg.Text)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
