// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rooms.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkNewJoinCode = `-- name: CheckNewJoinCode :many
SELECT id
FROM rooms
WHERE join_code = $1
`

func (q *Queries) CheckNewJoinCode(ctx context.Context, joinCode string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, checkNewJoinCode, joinCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE owner_id = $1
    AND id = $2
`

type DeleteRoomParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoom, arg.OwnerID, arg.ID)
	return err
}

const getRoomById = `-- name: GetRoomById :one
SELECT id, owner_id, name, description, join_code, created_at, updated_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomById(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomById, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoomOwnerIdByJoinCode = `-- name: GetRoomOwnerIdByJoinCode :one
SELECT owner_id
FROM rooms
WHERE join_code = $1
`

func (q *Queries) GetRoomOwnerIdByJoinCode(ctx context.Context, joinCode string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getRoomOwnerIdByJoinCode, joinCode)
	var owner_id uuid.UUID
	err := row.Scan(&owner_id)
	return owner_id, err
}

const getRoomsByMembership = `-- name: GetRoomsByMembership :many
SELECT r.id, owner_id, r.name, r.description, r.join_code, r.created_at, r.updated_at
FROM rooms r
JOIN room_memberships rm
    ON rm.room_id = r.id
WHERE rm.user_id = $1
`

func (q *Queries) GetRoomsByMembership(ctx context.Context, userID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByMembership, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoomsByOwner = `-- name: GetRoomsByOwner :many
SELECT id, owner_id, name, description, join_code, created_at, updated_at
FROM rooms
WHERE owner_id = $1
`

func (q *Queries) GetRoomsByOwner(ctx context.Context, ownerID uuid.UUID) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, getRoomsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (owner_id, name, description, join_code)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_id, name, description, join_code, created_at, updated_at
`

type InsertRoomParams struct {
	OwnerID     uuid.UUID `json:"owner_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	JoinCode    string    `json:"join_code"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, insertRoom,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.JoinCode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET name = COALESCE($3, name),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE owner_id = $1
    AND id = $2
RETURNING id, owner_id, name, description, join_code, created_at, updated_at
`

type UpdateRoomParams struct {
	OwnerID     uuid.UUID      `json:"owner_id"`
	ID          uuid.UUID      `json:"id"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoom,
		arg.OwnerID,
		arg.ID,
		arg.Name,
		arg.Description,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
