// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: room_memberships.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const joinRoom = `-- name: JoinRoom :exec
INSERT INTO room_memberships (user_id, room_id)
SELECT $1, id
FROM rooms
WHERE join_code = $2
`

type JoinRoomParams struct {
	UserID   uuid.UUID `json:"user_id"`
	JoinCode string    `json:"join_code"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.ExecContext(ctx, joinRoom, arg.UserID, arg.JoinCode)
	return err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_memberships rm
USING rooms r
WHERE rm.user_id = $1
  AND r.join_code = $2
`

type LeaveRoomParams struct {
	UserID   uuid.UUID `json:"user_id"`
	JoinCode string    `json:"join_code"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.ExecContext(ctx, leaveRoom, arg.UserID, arg.JoinCode)
	return err
}
