// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions
SET is_active = FALSE,
    ended_at = NOW(),
    updated_at = NOW()
`

func (q *Queries) EndSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, endSession)
	return err
}

const getSessions = `-- name: GetSessions :many
SELECT s.id, s.room_id, s.owner_id, s.name, s.is_active, s.started_at, s.ended_at, s.created_at, s.updated_at
FROM sessions s
JOIN rooms r
    ON s.room_id = r.id
WHERE s.owner_id = $1
    AND r.join_code = $2
`

type GetSessionsParams struct {
	OwnerID  uuid.NullUUID `json:"owner_id"`
	JoinCode string        `json:"join_code"`
}

func (q *Queries) GetSessions(ctx context.Context, arg GetSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessions, arg.OwnerID, arg.JoinCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OwnerID,
			&i.Name,
			&i.IsActive,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (owner_id, room_id, name) 
SELECT $1, r.id, $3
FROM rooms r
WHERE join_code = $2
RETURNING id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
`

type InsertSessionParams struct {
	OwnerID  uuid.NullUUID `json:"owner_id"`
	JoinCode string        `json:"join_code"`
	Name     string        `json:"name"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, arg.OwnerID, arg.JoinCode, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OwnerID,
		&i.Name,
		&i.IsActive,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :exec
UPDATE sessions
SET is_active = TRUE,
    started_at = NOW(),
    updated_at = NOW()
`

func (q *Queries) StartSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, startSession)
	return err
}
