// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const checkRoomMembershipBySessionId = `-- name: CheckRoomMembershipBySessionId :one
SELECT 1
FROM rooms r
LEFT JOIN room_memberships rm
    ON r.id = rm.room_id
    AND rm.user_id = $2
JOIN sessions s
    ON r.id = s.room_id
WHERE s.id = $1
    AND (r.owner_id = $2 OR rm.user_id IS NOT NULL)
LIMIT 1
`

type CheckRoomMembershipBySessionIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckRoomMembershipBySessionId(ctx context.Context, arg CheckRoomMembershipBySessionIdParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkRoomMembershipBySessionId, arg.ID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkRoomOwnershipBySessionId = `-- name: CheckRoomOwnershipBySessionId :one
SELECT 1
FROM rooms r
JOIN sessions s
    ON r.id = s.room_id
WHERE s.id = $1
    AND r.owner_id = $2
LIMIT 1
`

type CheckRoomOwnershipBySessionIdParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CheckRoomOwnershipBySessionId(ctx context.Context, arg CheckRoomOwnershipBySessionIdParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkRoomOwnershipBySessionId, arg.ID, arg.OwnerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE owner_id = $1
    AND id = $2
`

type DeleteSessionParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteSession, arg.OwnerID, arg.ID)
	return err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions
SET is_active = FALSE,
    ended_at = NOW(),
    updated_at = NOW()
WHERE owner_id = $1
    AND id = $2
`

type EndSessionParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) EndSession(ctx context.Context, arg EndSessionParams) error {
	_, err := q.db.ExecContext(ctx, endSession, arg.OwnerID, arg.ID)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OwnerID,
		&i.Name,
		&i.IsActive,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByRoomId = `-- name: GetSessionsByRoomId :many
SELECT id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
FROM sessions
WHERE room_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSessionsByRoomId(ctx context.Context, roomID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByRoomId, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OwnerID,
			&i.Name,
			&i.IsActive,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (owner_id, room_id, name) 
VALUES ($1, $2, $3)
RETURNING id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
`

type InsertSessionParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	RoomID  uuid.UUID `json:"room_id"`
	Name    string    `json:"name"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, arg.OwnerID, arg.RoomID, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OwnerID,
		&i.Name,
		&i.IsActive,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
