// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions
SET is_active = FALSE,
    ended_at = NOW(),
    updated_at = NOW()
`

func (q *Queries) EndSession(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, endSession)
	return err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OwnerID,
		&i.Name,
		&i.IsActive,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionsByRoomId = `-- name: GetSessionsByRoomId :many
SELECT id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
FROM sessions
WHERE room_id = $1
`

func (q *Queries) GetSessionsByRoomId(ctx context.Context, roomID uuid.UUID) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsByRoomId, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.OwnerID,
			&i.Name,
			&i.IsActive,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (owner_id, room_id, name) 
SELECT $1, r.id, $3
FROM rooms r
WHERE room_id = $2
RETURNING id, room_id, owner_id, name, is_active, started_at, ended_at, created_at, updated_at
`

type InsertSessionParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	RoomID  uuid.UUID `json:"room_id"`
	Name    string    `json:"name"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession, arg.OwnerID, arg.RoomID, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.OwnerID,
		&i.Name,
		&i.IsActive,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
