// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session_memberships.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const joinSession = `-- name: JoinSession :exec
INSERT INTO session_memberships (user_id, session_id)
VALUES ($1, $2)
`

type JoinSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) JoinSession(ctx context.Context, arg JoinSessionParams) error {
	_, err := q.db.ExecContext(ctx, joinSession, arg.UserID, arg.SessionID)
	return err
}

const leaveSession = `-- name: LeaveSession :exec
DELETE FROM session_memberships
WHERE user_id = $1
  AND session_id = $2
`

type LeaveSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SessionID uuid.UUID `json:"session_id"`
}

func (q *Queries) LeaveSession(ctx context.Context, arg LeaveSessionParams) error {
	_, err := q.db.ExecContext(ctx, leaveSession, arg.UserID, arg.SessionID)
	return err
}
