package utils

var ErrBadRequest = "BAD_REQUEST"
var ErrUserAlreadyExists = "USER_ALREADY_EXISTS"
var ErrInvalidCredentials = "INVALID_CREDENTIALS"
var ErrInvalidRefreshToken = "INVALID_REFRESH_TOKEN"
var ErrInvalidAccessToken = "INVALID_ACCESS_TOKEN"
var ErrMissingAccessToken = "MISSING_ACCESS_TOKEN"
var ErrUserNotFound = "USER_NOT_FOUND"
var ErrValidationFailed = "VALIDATION_FAILED"
var ErrBadResponse = "BAD_RESPONSE"
var ErrDbtxFail = "DBTX_FAIL"
var ErrMarshalFail = "MARSHAL_FAIL"
var ErrHashFail = "HASH_FAIL"
var ErrJwtFail = "JWT_FAIL"
var ErrRefreshFail = "REFRESH_FAIL"
var ErrTxBeginFail = "TX_BEGIN_FAIL"
var ErrTxCommitFail = "TX_COMMIT_FAIL"
var ErrRefreshRevokeFail = "REFRESH_REVOKE_FAIL"
var ErrGetUserDataFail = "GET_USER_DATA_FAIL"
var ErrCreateJoinCodeFail = "CREATE_JOIN_CODE_FAIL"
